server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/Parkinglot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/*
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/
  devtools:
    restart:
      exclude: static/** , jmu/** , application.yml
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: jmu.vo
  config-location: classpath:mybatis-config.xml

#showSql
logging:
  level:
    jmu.mapper: debug

# 配置 RestTemplate
restTemplate:
  # 设置连接超时时间为 5 秒
  connect-timeout: 5000
  # 设置读取超时时间为 10 秒
  read-timeout: 10000

api:
  url: http://127.0.0.1:8800/LPR



