server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/Parkinglot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/*
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/
  devtools:
    restart:
      exclude: static/** , jmu/** , application.yml
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: jmu.vo
  config-location: classpath:mybatis-config.xml

#showSql
logging:
  level:
    jmu.mapper: debug



